### ISSUE TITLE
toggling collapsed inline

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#99]
Hi, currently the toggle for collapsed inline has two main "zones": one is the blue eye icon, and the other is the whole header. The whole header is very practical as a way to toggle inlines, but there are currently two issues:
- first, there is no visual cue that the header is in fact clickable (some change in color on hover would help suggesting that it can be clicked)
- second, the inline label itself is, surprisingly, not clickable.

Finally, it might be clearer to put the blue eye on the left, instead of just beside the Delete checkbox (it's a bit dangerous to have these guys too close). In fact, if the whole header is clickable, and with a visual cue, then the blue eye might not even be needed!

**Comment by abidibo** [comment]
Hi @etanter ,

I've pushed some changes in the develop branch.

> first, there is no visual cue that the header is in fact clickable (some change in color on hover would help suggesting that it can be clicked)

I've added a cursor pointer on the whole header

> second, the inline label itself is, surprisingly, not clickable.

It doesn't happen to me, which browser?

> Finally, it might be clearer to put the blue eye on the left, instead of just beside the Delete checkbox (it's a bit dangerous to have these guys too close). In fact, if the whole header is clickable, and with a visual cue, then the blue eye might not even be needed!

I don't like the visual effect of having the icon on the left side

ref 06b41e679725213968f9a2624fc660c170d1b905

**Comment by etanter** [comment]
I'm on Chrome (on mac OS), but note that I'm on baton v1.9.3 (because of #86, sticking to the old user menu bar)

regarding the blue eye, if you leave it on the left, could it come before the Delete checkbox instead of after?

**Comment by etanter** [comment]
(I observe the click-but-not-expand behavior on the inline title in both Chrome and Safari)

**Comment by abidibo** [comment]
Quite strange, this commit (https://github.com/otto-torino/django-baton/commit/75a916b19a73535b5ad62ec2358b057341523e6a) should have fixed it

**Comment by etanter** [comment]
I just tried with the develop branch (via `pip install "git+ssh://git@github.com/otto-torino/django-baton.git@develop"`), and I see the icon on hover (great!) but still have the problem that clicking the title does not trigger anything.

**Comment by abidibo** [comment]
I don't like the eye icon on the left, this is why:

![Screenshot from 2020-10-08 15-32-33](https://user-images.githubusercontent.com/444093/95465704-c115f080-097b-11eb-86f5-cf51d44fe447.png)

What I can do, is to separate a bit more the icon from the delete checkbox:

![Screenshot from 2020-10-08 15-33-54](https://user-images.githubusercontent.com/444093/95465764-d5f28400-097b-11eb-9bb1-5d118569333e.png)

ref 5cdd104063ac42da31b3813ad138ff98caf9f3ab

**Comment by etanter** [comment]
oh I see, hadn't thought about cases where Delete isn't present. Good point. Yes, a bit more distance is good

**Comment by abidibo** [comment]
@etanter , I've just tried with chrome and safari with a mac mini and a MacBook pro and I can't reproduce the click on label issue.
If you inspect the dom, can you see the `.entry-collapse-full-toggler` as a label parent?

**Comment by etanter** [comment]
yeah, I was tracking it down, and realized it's due to some modification of the `edit_inline/stacked.html` template. I'll look further into the details, but clearly the problem is on my side :/

**Comment by etanter** [comment]
It was because I added a span to add a tooltip, and that breaks the overall link. I changed the span, adding a separate info icon and limiting the tooltip to that icon, and it's back to normal.
Sorry for the noise, and thanks for adding the cursor pointer!
